### ISSUE TITLE
Usage on jupyterhub-sngleuser clarify

### ISSUE THREAD

**Issue by andrii29** [lydian/jupyterlab_hubshare#5]
Hi,
Got error with this plugin.

Use it in jupyterhub (with lab) and want to change share links from
 https://hub.example.com/user/andrew.k/lab/tree/ak/Untitled.ipynb 
to 
https://hub.example.com/user-redirect/lab/tree/ak/Untitled.ipynb

Configuration file

```

cat /etc/jupyter/jupyter_notebook_config.py 
c.HubShare.use_preview = False
c.HubShare.file_path_template = "{path}"

```

It works when I build image and use on local machine with jupyter-lab, but when started in jupter-hub I got error
`PUT https://hub.appgrowth.com/user/andrew.k/jupyterlab_hubshare/share-url?1622186067216 - [HTTP/2 404 Not Found 212ms]`
Is it possiple to disable any PUT requests and just replace  **user/andrew.k** -> **user-redirect** in url

TY!

Regards,
Andrii

**Comment by lydian** [comment]
The PUT is required to get the encoded path.  It looks like you may failed to install the server extension. Would you mind double check if your extension installed successfully ?

**Comment by andrii29** [comment]
hi,
```
jupyter server extension list
Config dir: /usr/local/etc/jupyter
...
    - Validating jupyterlab_hubshare...
      jupyterlab_hubshare 0.2.1 OK
```


```
jupyter labextension list
JupyterLab v3.0.16
/usr/local/share/jupyter/labextensions
...
        jupyterlab_hubshare v0.2.1 enabled OK (python, jupyterlab_hubshare)
```

It work's when i start server with `jupyter-lab` command, but fails with 404 when start server with `jupyterhub-singleuser --SingleUserNotebookApp.default_url=/lab`

**Comment by lydian** [comment]
ah, I get the issue. I'll work on a fix this weekend. Thanks for reporting!

**Comment by lydian** [comment]
i found a different bug, but that seems to be different from what you're seeing for the PUT issue. 
Basically the current version failed with no preview mode because of missing the `lab/tree` in the path. 
However, I couldn't reproduce the 404 PUT error.  I am wondering if you could find any error logs when you start the jupyter server. The 404 on put is definitely  related to unable to find the server extension though.

**Comment by andrii29** [comment]
hi,
see no errors in log (only info and warnings). All other extensions installed via pip are working as expected. Maybe extension register itself on `/jupyterlab_hubshare` instead of `/user/andrew.k/jupyterlab_hubshare`?

**Comment by lydian** [comment]
nah, the `/user/<user_name>` is required, meaning that you're using the server extension installed on single user notebook server,  without that, it means that you're using the hub service instead.   Can you make sure that you're installing the server extension on the single user server?  or you can share with me your jupyterhub_config.py and singleuser_config.py so that I can test what went wrong ?

**Comment by andrii29** [comment]
hi,
use default config for hub from https://github.com/jupyterhub/zero-to-jupyterhub-k8s (with google oauth)

All command below executed on singleuser notebook
startup command
```
jupyterhub-singleuser
--ip=0.0.0.0
--port=8888
--SingleUserNotebookApp.default_url=/lab
```

use only this config, no other config files are present on singleuser
_cat /etc/jupyter/jupyter_notebook_config.py_ 
```
c.HubShare.use_preview = False
c.HubShare.file_path_template = "{path}"
```


_jupyter server extension list_
```
    jupyterlab_hubshare enabled
    - Validating jupyterlab_hubshare...
      jupyterlab_hubshare 0.2.3 OK
```


jupyter lab extension list
```
    jupyterlab_hubshare enabled
    - Validating jupyterlab_hubshare...
      jupyterlab_hubshare 0.2.3 OK
```

on web console (F12 in browser)
`JupyterLab extension jupyterlab_hubshare is activated!`
press "Copy Sharable Link"
```
PUT https://hub.example.com/user/andrew.k/jupyterlab_hubshare/share-url?1623046763010
[HTTP/2 404 Not Found 176ms]
```
